### ISSUE TITLE
I'm stuck in one step...

### ISSUE THREAD

**Issue by DemitriLatet** [DanielBatesUK/cloudflare-api-dns-dynamic-ip#1]
After typing "jq . cloudflare-dns-update_dnslist.json" to get the "DNS ID", nothing seems happenned, no error message, nothing... :(

**Comment by DanielBatesUK** [comment]
Is the DNS list file being created? Do you get output with `cat cloudflare-dns-update_dnslist.json`?

**Comment by DemitriLatet** [comment]
Hi, thanks for the feedback.
Yes, the file has been created "mydomain_com_dnslist.json", I've opened with "nano" but seems to be an empty file.

**Comment by DemitriLatet** [comment]
Do I need to keep the "[]" for the cloudflare credentials?

**Comment by DanielBatesUK** [comment]
> Do I need to keep the "[]" for the cloudflare credentials?

No

```Shell
# Cloudflare API token and Website Zone ID
TOKEN="a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6"
ZONEID="a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6"

# DNS Record ID
DNSID="a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6"
```

**Comment by DanielBatesUK** [comment]
> Hi, thanks for the feedback. Yes, the file has been created "mydomain_com_dnslist.json", I've opened with "nano" but seems to be an empty file.

I'm a little concerned it's blank. I would at least expect an error message back from Cloudflare.

**Comment by DanielBatesUK** [comment]
I've just committed some updates, removing those braces in the script and updating the readme.

You should see the received JSON body from Cloudflare in the terminal after running the script. It is difficult to read the matrix style wall-of-text you'll get back. But it's not impossible. Using `jq` does make it a hell of a lot easier.

**Comment by DemitriLatet** [comment]
Thank you, it's working perfect now. :D
Just a little error in the syntax: "sudo contab -e" instead of "sudo crontab -e".

**Comment by DanielBatesUK** [comment]
Brilliant. That's good to here 👍

> Just a little error in the syntax: "sudo contab -e" instead of "sudo crontab -e".

Thanks for the heads-up. I've updated the readme.
